### ISSUE TITLE
AnitaB.org Challenge Problem 

### ISSUE THREAD

**Issue by sarimurrab** [saharkausar/AnitaBorg-Python-Certification-Course#1]
**_FEEDBACK:_**
[Your problem submission](https://github.com/saharkausar/AnitaBorg-Python-Certification-Course/blob/master/Week%202%20Coding%20Challenges/Sequence%20Types/seqList.py)

1. You did it well but forgot to print the answer as highlighted by selector
![image](https://user-images.githubusercontent.com/35756749/83379039-34b95700-a3f8-11ea-8732-eae0242742e0.png) 
use 
`print("There are {} unique elements in L1".format(len(newList)))`
at appropriate place.

2. You created a function for finding the unique elements which is
```
#Function that calculates the number of unique elements in a list
def calcListEl(ls):
    x = []
    for a in ls:
        if a not in x:
            x.append(a)
    return x
```
It is giving out the correct expected output. 
But If we try to think this problem in more python way, then python data structure **set** comes into the mind. 
So alternatively we can go like this:
```
#Converting it to set() because set contains only unique elements.
s1 = set(L1)
length = len(s1)
print("There are {} unique elements is L1.".format(length))
```

**Comment by saharkausar** [comment]
Thank you for your helpful feedback @sarimurrab! I went ahead and addressed those notes with an updated revision! Glad to see that there is a way that is simple and pythonic. Cheers!
